

spring:
  thymeleaf:
    # 模板模式：HTML5
    mode: HTML
    # 编码
    encoding: UTF-8
    # 内容类型值
    content-type: text/html
    # 是否启用缓存
    cache: false
    # 前缀
    prefix: classpath:/static/
    # 后缀
    suffix: .html

server:
  port: 8080
